In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from Convolutional_Layer import Convolutional_Layer
import time

# Load and preprocess the data
digits = pd.read_csv('Datasets/digit_train.csv')
digit = np.array([
    np.array([digits.values[0][1:].reshape(28, 28)])
])
label = np.array([
    digits.values[0][0]
])

In [2]:
from Convolutional_Layer import Convolutional_Layer
from Dense_Layer import Dense_Layer
from Output_Layer import Output_Layer
from Flatten import Flatten
from Model import Model

model = Model(Layers=[
    Convolutional_Layer(filters=3, filter_size=3, stride=1, padding=1, activation_func=None), # layer 0
    Flatten(), # layer 1
    Dense_Layer(input_shape=3 * 28 * 28, output_shape=5, activation_func="relu"), # layer 2
    Dense_Layer(input_shape=5,output_shape=6, activation_func="relu"), # layer 3
    Output_Layer(input_shape=6,output_shape=1) # layer 4
])

model.forward_pass(digit[0])
error = model.fit(digit, label, learning_rate=0.001, epochs=10)
plt.plot(error)

IndexError: index 1 is out of bounds for axis 0 with size 1

In [132]:
from Model import *

X = np.random.randn(1,1)

my_model = Model(Layers=[
    Dense_Layer(input_shape=1,output_shape=10, activation_func="relu"),
    Dense_Layer(input_shape=10,output_shape=10, activation_func="relu"),
    Output_Layer(input_shape=10,output_shape=1)
])

my_model.forward_pass(X[0])
error = my_model.fit(X, X, learning_rate=0.001, epochs=1)

Dense_Layer [-0.         -0.62918817 -0.         -0.         -0.4177815  -0.22966532
  0.44284459  0.07056222  0.12400066  0.06523363]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dense_Layer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dense_Layer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dense_Layer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dense_Layer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Dense_Layer [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Epoch 1/1, Average Loss: 2.850270605584982
